deploying to netlify
pupilfirst/wd301-scripts pull request #152
Opened 2023-03-15 11:06 UTC by vikispeaks

2023-07-14 12:50 UTC, mjzac requested changes

2023-07-14 12:50 UTC, mjzac commented on react-router/deploying-to-netlify/README.md
> +Next, specify the directory to deploy, which in this case is `build`.
`Vite` by default uses `dist` as output directory, not build. We changed the output directory in `vite.config.js` to make output directory match what CRA uses.

2023-07-17 06:25 UTC, vikispeaks commented on react-router/deploying-to-netlify/README.md
> +Next, specify the directory to deploy, which in this case is `build`.
I checked in the latest l8 @mjzac, and we still seem to have `build` as the output dir. So had reused it. Should we update the solution repo too in that case? I would need to change the PWA script if so.

2023-07-17 07:46 UTC, mjzac commented on react-router/deploying-to-netlify/README.md
> +Next, specify the directory to deploy, which in this case is `build`.
@vikispeaks That is because of the following lesson https://www.pupilfirst.school/targets/19547

>Configuring output directory

>Vite by default outputs the build to dist folder relative to the project root. You can customize this by adding outDir key under build in vite.config.js file.

```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default ({ mode }) => {
  return defineConfig({
    build: {
      outDir: 'build',
    },
    plugins: [react()],
    define: {
      "process.env.NODE_ENV": `"${mode}"`,
    },
  });
};
```

2023-07-18 10:59 UTC, merged